language: node.js
node_js:
- '10'
cache:
  directories:
  - node_modules
install:
- npm install
deploy:
  provider: heroku
  api_key:
    secure: amUg3E96+jfv1IrxfbcUSsfQKah/QAENKjUl8thM4GSJFMVnSMwn7XyGyenVDTgN61nxYQP1Z8/Or/jdfJ2UtcNIRdF0YsRKC6VYdrgbfDqywyCe9ZvLQ6b8y1hmH8JUw3p84FjVU0Ud7+94xjSi1xjs+jMxchJF1RKPPOyTr8BlQIHz6wikov/27aRVzgOvlDC8T8f1z3JP6vV/qY4mx8Xy0H7vRHMXXVy5vhfFYZaf5Ob6ydNgcmuC/202cXRcKjgSP8ivS1eYCOD/xuaYO7ixow+WaW3J/DU4ispnZLkaKnY2JTigDjQgmfP0xY265r85O8yjxNfTTxSzS0okdoasIyDmNxHaNHEEbcY0X2OFLmxCNBXr6e1Dgx5+mR6nWg7zz55UUKuiOzXFe7eyzyKZBxNJCfcT49DeAOKM+61U5iFE51C/ANWPZvZfzQW6M35fljgaaIyXtN2K6vKQf9cnv7NXYXqOJXNcsUPiTFNGiAFNUCrmWxO3BldbmJHZsuf3jYiTa/yp62+FwOuxZEYM78u+aRHclZHW8rVNItvTDAQz6yYdSUjcD3ESgEIEn4NkVLb1Xj14B4t8DzG1bwBg8NiaDbDn19W4EtcfpYA+E2BSV0SXPfhg5YwWMuNW+E44/Con0kMq9ycYAHRLkPaxRf29qIx/2eH5RScQHfQ=
  app: anneshandmade-apollo-prod
  on:
    repo: benjaminadk/annes-handmade-backend
